# Generated by Django 5.0.6 on 2024-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendormodel',
            old_name='vendor_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='acknowledgment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='', editable=False, max_length=20),
        ),
    ]
